import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-50 dark:bg-black`}>
        <nav className="w-full bg-white dark:bg-zinc-900 shadow flex items-center px-6 py-3 gap-8">
          <Link href="/" className="text-xl font-bold text-indigo-700 dark:text-indigo-300 tracking-tight hover:underline">TTRPG Story Hub</Link>
          <ul className="flex gap-4 text-base font-medium">
            <li>
              <Link href="/" className="text-zinc-700 dark:text-zinc-200 hover:text-indigo-600 dark:hover:text-indigo-400">Home</Link>
            </li>
            <li>
              <Link href="/campaigns" className="text-zinc-700 dark:text-zinc-200 hover:text-indigo-600 dark:hover:text-indigo-400">Campaigns</Link>
            </li>
            <li>
              <Link href="/characters" className="text-zinc-700 dark:text-zinc-200 hover:text-indigo-600 dark:hover:text-indigo-400">Characters</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
